---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - files:
      - ./config-defaults.yaml
    name: model-serving-config-defaults

transformers:
  - ./default/metadataLabelTransformer.yaml
