apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-modelmesh
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: odh-manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
        - name: monitoring-namespace
          value: opendatahub
        overlays:
          - odh-model-controller
        repoRef:
          name: manifests
          path: manifests/opendatahub
      name: model-mesh
  repos:
    - name: odh-manifests
      uri: https://api.github.com/repos/opendatahub-io/odh-manifests/tarball/master
    - name: manifests
      uri: https://api.github.com/repos/red-hat-data-services/modelmesh-serving/tarball/main
  version: master
