---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../manager
  - ./service.yaml

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - params.yaml

patches:
  - path: ./controller_manager_patch_replace.yaml
