---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../manager/manager.yaml
  - ./service.yaml

configMapGenerator:
  - files:
      - ../default/config-defaults.yaml
    name: model-serving-config-defaults

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - params.yaml

patches:
  - path: ./controller_manager_patch_replace.yaml
