apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-model-controller
  namespace: system
spec:
  replicas: 3
  template:
    spec:
      containers:
        - command:
          args:
            - "--monitoring-namespace"
            - "$(MONITORING_NS)"
          image: $(odh-model-controller)
          env:
            - name: MONITORING_NS
              value: $(monitoring-namespace)
