---
apiVersion: v1
kind: Secret
metadata:
  name: model-serving-etcd
stringData:
  etcd_connection: |
    {
      "endpoints": "http://etcd:2379",
      "root_prefix": "modelmesh-serving",
      "userid": "root",
      "password": "<etcd_password>"
    }
